/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RX13_CMT                               */
/*      FILE         :  RX13_CMT.c                             */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>

#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

typedef unsigned char u08;
typedef unsigned short u16;
typedef unsigned long u32;

//used registers:

	//9.2.2 System Clock Control Register 3 (SCKCR3)
#define SYSTEM_SCKCR3	*(u16 volatile *const)0x00080026
	//9.2.1 System Clock Control Register (SCKCR)
#define SYSTEM_SCKCR	*(u32 volatile *const)0x00080020
	//9.2.8 High-Speed On-Chip Oscillator Control Register (HOCOCR)
#define SYSTEM_HOCOCR	*(u08 volatile *const)0x00080036
	//9.2.9 Oscillation Stabilization Flag Register (OSCOVFSR)
#define SYSTEM_OSCOVFSR *(u08 volatile *const)0x0008003C
	//11.2.2 Module Stop Control Register A (MSTPCRA)
#define MSTPCRA			*(u32 volatile *const)0x00080010
	//12.1.1 Protect Register (PRCR)
#define SYSTEM_PRCR		*(u16 volatile *const)0x000803fe
	//17.3.1 Port Direction Register (PDR)
#define PORT7_PDR		*(u08 volatile *const)0x0008c007
	//21.2.1 Compare Match Timer Start Register 0 (CMSTR0)
#define CMT_CMSTR0		*(u16 volatile *const)0x00088000
	//21.2.2 Compare Match Timer Control Register (CMCR)
#define CMT1_CMCR		*(u16 volatile *const)0x00088008
	//21.2.3 Compare Match Counter (CMCNT)
#define CMT1_CMCNT		*(u16 volatile *const)0x0008800A


u16 volatile timed;
#define time( code )\
	do{ timed=CMT1_CMCNT; {code;} timed=CMT1_CMCNT-timed; } while(0)

int main(void)
{	SYSTEM_PRCR = 0xa50b;		//PRCR=KEY|PRC3|PRC1|PRC0;//all protection off

	//clock setup to operate at HOCO 32MHz, PCLKB /64 = 500 kHz:
	while( !((1UL<<3) & SYSTEM_OSCOVFSR) )//!BITGET(OSCOVFSR,HCOVF)
		SYSTEM_HOCOCR = 0x00;	//HOCO on
	//* already on in debug-mode with HOCO-clock setting?
	SYSTEM_SCKCR = 0x00000000	//div = 1, except...
	| (6UL<<8) | (6UL<<0);		//PCKB:64 PCKD:64
	SYSTEM_SCKCR3 = (1UL<<8);	//clock source = HOCO

	//start CMT1, period 0xffff(default), PCLKB/512:
	MSTPCRA &=~(1UL<<15);		//BITCLR(MSTPCRA,CMT01);
	CMT1_CMCR = 0x0080 | (3UL<<0);//f_count = PCLKB/512
	CMT_CMSTR0 |= (1UL<<1 );	//BITSET(CMSTR0,STR1);

	SYSTEM_PRCR = 0xa500;		//PRCR=KEY | 0;//all protection on

time( );//empty reference time

	while(1) {

		PORT7_PDR = 0x00;//(default), breakpoint 1

time(	PORT7_PDR = 0x00;//(default), check time
);
		PORT7_PDR = 0x00;//(default), breakpoint 2

    }
return 0;
}
